version: '3.8'

services:
 backend:
  build:
   context: .
  ports:
   - 8000:8000
  volumes:
   - ./:/app:ro
  restart: always
  depends_on:
   - postgresdb

 frontend:
  build:
   context: ../../js/kaffee-kasse-frontend
  ports:
   - 80:80
  volumes:
   - ../../js/kaffee-kasse-frontend/dist/kaffee-kasse-frontend:/usr/share/nginx/html:ro
   - $HOME/certs/pem:/usr/share/nginx/ssl/
  depends_on:
   - backend

 postgresdb:
  image: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_PASSWORD=pw
  volumes:
   - postgres:/var/lib/postgresql/data
  restart: always

volumes:
  postgres:
